### ISSUE TITLE
Please consider registering this

### ISSUE THREAD

**Issue by scopatz** [DangerOnTheRanger/xonsh-apt-tabcomplete#1]
We'd love to have a entry for this in main xonsh repo. http://xon.sh/tutorial_xontrib.html#tell-us-about-your-xontrib Let us know if you have any questions. Thanks!

**Comment by DangerOnTheRanger** [comment]
Made a pull request here: https://github.com/xonsh/xonsh/pull/1258

I'll be sure to close this issue soon as the PR gets worked out - thanks for the reminder!

**Comment by scopatz** [comment]
Thanks @DangerOnTheRanger!
