### ISSUE TITLE
Latest version not available on pypi

### ISSUE THREAD

**Issue by danmou** [DangerOnTheRanger/xonsh-apt-tabcomplete#7]
Version 1.5.0 is not on [pypi](https://pypi.org/project/xonsh-apt-tabcomplete/).

**Comment by DangerOnTheRanger** [comment]
Sorry about that - I've made a new 0.1.6 release with a bumped patch level and [uploaded it to PyPI](https://pypi.org/project/xonsh-apt-tabcomplete/).
