### ISSUE TITLE
Add preview image to the repository

### ISSUE THREAD

**Issue by anki-code** [DangerOnTheRanger/xonsh-apt-tabcomplete#9]
Hi! Thank you for the xontrib!

Please add the preview image to the repository: "Settings" - "Options" - "Social preview". It allows to show preview image in Github Topics and social networks.

You already have the image for this:

![image](https://user-images.githubusercontent.com/1708680/103137982-de3a9f80-46de-11eb-850d-f1bbb89be7d7.png)

Thanks!

**Comment by DangerOnTheRanger** [comment]
Added, thanks!
